### ISSUE TITLE
tmp file recompilation loop followed + watcher crash

### ISSUE THREAD

**Issue by IceDragon200** [emberwatch/ember-cli-typescript#11]
The title sums up the entire issue.

Adding this addon to a new ember project and doing `ember s` will show tmp files being tracked followed by a watcher crash.

If it does manage to compile, the typescript compiler continues to loop trying to compile the temp files (over and over and over and over and over...)

**Steps to repeat:**

```
ember new typescript-loop
# wait for that to finish
cd typescript-loop
ember install "ember-cli-typescript@emberwatch/ember-cli-typescript"
# wait again
ember s
```

The following gist contains an extract from the logs
https://gist.github.com/IceDragon200/3edbb19f54e883d1cf6e123220c2878d

Versions and stuff:

* Host System - Arch Linux x86_64 (vanilla kernel)
* Typescript 2.1.5 (globally available)
* Node 7.4.0 (because Arch Linux)
* Ember 2.8, 2.9. 2.10 (all of them failed)

I would also like to point out, installing the addon the first time will fail with "unable to find typescript", forcing you to install typescript in the project first and then trying again to install this.

**Comment by cascalheira** [comment]
As workaround, if you compile and install watchman (https://facebook.github.io/watchman/docs/install.html), it should start working.

**Comment by rwjblue** [comment]
The reason this happens is that we are creating a tree for the root of the project here: https://github.com/emberwatch/ember-cli-typescript/blob/master/lib/typescript-preprocessor.js#L67

The issue is that watching the parent directory of the tmp dir causes infinite recursion as ever rebuild (which causes changes in tmp) then causes another rebuild. 

The solution is to use broccoli-source to create an UnwatchedDir instead of passing process.cwd to find.
