### ISSUE TITLE
Getting warnings while the app builds

### ISSUE THREAD

**Issue by Prabhakar-Poudel** [emberwatch/ember-cli-typescript#49]
Recently I started using `ember-typescript` in my existing project.
So I started by migrating few files to `typescript` (component1, component2 and util1).
And when I run embe build, I see few build warnings I have not been able to figure out why.   
Below is the warnings i see in console.

```
Cannot write file '/app/file1.js' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
/app/components/component1.ts(3,18): Cannot find module 'ember-uuid'.
/app/components/component2.ts(2,18): Cannot find module 'ember-uuid'.
/app/utils/util1.ts(4,18): Cannot find module 'ember-uuid'.
/myApp/components/component1.ts(2,23): Cannot find module '../file1'.
/myApp/components/component1.ts(3,18): Cannot find module 'ember-uuid'.
/myApp/components/component2.ts(2,18): Cannot find module 'ember-uuid'.
/myApp/utils/util1.ts(3,23): Cannot find module '../file1'.
/myApp/utils/util1.ts(4,18): Cannot find module 'ember-uuid'.
```

Everything worked normally when these were `js` files. They still work fine and as expected, but these build errors are something I could not understand.   
Any help is greatly appreciated.

Note: `app/file1.js` is a `js` file imported in `ts` files. And also `ember-uuid` is a [node package](https://github.com/ivanvanderbyl/ember-uuid) I'm using and this too is imported in these `ts` files.

**Comment by chriskrycho** [comment]
@Prabhakar-Poudel the problem here is that you don't have any types for those, and it doesn't know how to import them. The easiest way to do it is to add [typing files] which define those modules (even if it's just using `any`) so TS knows what to do with them.

[typing files]: http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

These won't prevent your build from *working*—we manage JS and TS separately using Babel and the TypeScript compiler respectively—but they do let you know that TS doesn't know what to do with those files.
